### ISSUE TITLE
A1 - Dani

### ISSUE THREAD

**Issue by Bramd3** [curio-lesmateriaal/pra-b4-2024-pra-b4-bram-dani-kevin#1]

**Comment by GwnDani** [comment]
A1 – Als bezoeker wil ik op het scherm alle foto’s zien, zodat ik mijn eigen actiefoto kan opzoeken en het nummer kan doorgeven aan de kassa.

- 🛠️ Technische tip:
  - Je hoeft niet te kijken naar de tijden. Toon simpelweg alle foto’s van vandaag.
  - Pas de bestaande foreach loops aan en gebruik if statements om te filteren op naam.
  - In C# kun je het dagnummer opvragen op deze manier (0 = Zondag t/m 6 = Zaterdag):
  
  - Zoek zelf op hoe je van de mapnaam zoals “2_Dinsdag” alleen het eerste stukje kunt pakken, zodat je dit kunt vergelijken met het dagnummer van vandaag.
